spring.application.name=photoblog
spring.datasource.url=jdbc:postgresql://localhost:5432/photoblog
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html

spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8

logging.level.root=INFO
logging.level.it.uniroma3.siw.photoblog=DEBUG

# foto caricate dall'admin in locale e poi /uploads/**
app.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB
